# Generated by Django 2.1.7 on 2019-07-05 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_email', models.CharField(max_length=100, verbose_name='Abone Maili')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
            },
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_baslik', models.CharField(max_length=150, verbose_name='Makale Başlığı')),
                ('makale_yayintarihi', models.DateField(verbose_name='Makale Yayın Tarihi')),
                ('makale_mesaj', ckeditor.fields.RichTextField()),
                ('makale_slug', models.SlugField(unique=True)),
                ('makale_kategori', models.CharField(choices=[('hakaret', 'Hakaret'), ('yaralama', 'Yaralama'), ('orgutsuclari', 'Örgüt Suçları'), ('uyusturucumaddesuclari', 'Uyuşturucu Madde Suçları'), ('beyazyakalisuclari', 'Beyaz Yakalı Suçları')], max_length=50, verbose_name='Makale Kategorisi')),
                ('makale_meta_description', models.CharField(max_length=350, verbose_name='Makale Meta Açıklaması(SEO İÇİN)')),
                ('image625x400', models.ImageField(upload_to='', verbose_name='625x400 Resim')),
                ('image297x400', models.ImageField(upload_to='', verbose_name='297x400 Resim')),
                ('image240x160', models.ImageField(upload_to='', verbose_name='240x160 Resim')),
                ('image500x287', models.ImageField(upload_to='', verbose_name='500x287 ve 406x279 Resim')),
                ('image100x85', models.ImageField(upload_to='', verbose_name='100x85 Resim')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ('-makale_yayintarihi',),
            },
        ),
        migrations.CreateModel(
            name='MakaleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_tag_isim', models.CharField(max_length=100, verbose_name='Makale Tag')),
            ],
            options={
                'verbose_name': 'Makale Etiketi',
                'verbose_name_plural': 'Makale Etiketleri',
            },
        ),
        migrations.AddField(
            model_name='makaleler',
            name='tag',
            field=models.ManyToManyField(to='mainapp.MakaleTags'),
        ),
    ]
